version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-no-password
    environment:
      POSTGRES_USER: myuser       # Replace with your preferred username
      POSTGRES_DB: mydatabase     # Replace with your preferred database name
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
